### ISSUE TITLE
How to use it with images?

### ISSUE THREAD

**Issue by Madhav-94** [SimenHolmestad/Privacynator#1]
I wanted to use it with jpeg images, can you provide some information for it

**Comment by SimenHolmestad** [comment]
The current version is meant to work with videos, but if you want to change it to work on images, it would probably not be that difficult :)

The videos are loaded using OpenCV, so if you use OpenCV to load you jpeg images, they would probably be on the right format. See this: https://docs.opencv.org/3.1.0/dc/d2e/tutorial_py_image_display.html 

When you have an image on the right format, you can probably pass it through one of the functions like this one to get the anonymized image before saving it: https://github.com/SimenHolmestad/Privacynator/blob/3ee7c7c0c3bcdf00fe4c775c691cf97d5356ea73/video_operations/blur.py#L11 

Good luck!
